name: hello

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install python
    - name: Install Requirements
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt
    - name: Execute
      run: |
        python downloadblob.py
        echo Executing downloadblob.py
        python uploadblob.py
        echo Executing uploadblob.py
        python main.py
        echo Executing main.py
