name: hello

on: [push]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.6.14"]

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} 
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute
      run: |
        python downloadblob.py
        echo Executing downloadblob.py
        python uploadblob.py
        echo Executing uploadblob.py
        python main.py
        echo Executing main.py
